version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - cloud-network

  cloud-1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST_URL=cloud-1
    command: [ "poetry", "run", "python", "/app/src/entrypoint.pyx", "-f", "/mnt/multicloud-fs", "-r", "/tmp/rootpath", "-p", "5000", "-u", "redis://redis:6379" ]
    depends_on:
      - redis
    networks:
      - cloud-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse

  cloud-2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST_URL=cloud-2
    command: [ "poetry", "run", "python", "/app/src/entrypoint.pyx", "-f", "/mnt/multicloud-fs", "-r", "/tmp/rootpath", "-p", "5001", "-u", "redis://redis:6379" ]
    depends_on:
      - redis
    networks:
      - cloud-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse

networks:
  cloud-network:
    driver: bridge