[tool.poetry]
name = "multicloud-file-system"
version = "0.1.0"
description = ""
authors = ["Wojciech Przybytek <wprzybytek@student.agh.edu.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fuse-python = "^1.0.7"
python-dotenv = "^1.0.1"
grpcio = "^1.64.1"
grpcio-tools = "^1.64.1"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
isort = "^5.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
