kind: Service
apiVersion: v1
metadata:
  name: multicloud-csi-controller-service
  namespace: multicloud-system
spec:
  selector:
    app: multicloud-csi-controller
  ports:
    - port: 6379
      name: redis

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: multicloud-csi-controller
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multicloud-csi-controller
  template:
    metadata:
      labels:
        app: multicloud-csi-controller
    spec:
      serviceAccountName: multicloud-csi-controller
      containers:
        - name: redis
          image: {{ .Values.images.redis.repository }}:{{ .Values.images.redis.tag }}
          imagePullPolicy: {{ .Values.images.redis.pullPolicy }}
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 15
          volumeMounts:
            - name: redis-data
              mountPath: /data
        - name: csi-provisioner
          image: {{ .Values.images.controllerCsiProvisioner.repository }}:{{ .Values.images.controllerCsiProvisioner.tag }}
          imagePullPolicy: {{ .Values.images.controllerCsiProvisioner.pullPolicy }}
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--feature-gates=Topology=true"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: {{ .Values.images.controllerCsiAttacher.repository }}:{{ .Values.images.controllerCsiAttacher.tag }}
          imagePullPolicy: {{ .Values.images.controllerCsiAttacher.pullPolicy }}
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: multicloud-csi-plugin
          image: {{ .Values.images.csiPlugin.repository }}:{{ .Values.images.csiPlugin.tag }}
          imagePullPolicy: {{ .Values.images.csiPlugin.pullPolicy }}
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--redis-url=redis://localhost:6379"
            - "--node-url=null"
          env:
            - name: SKIP_NODE_MOUNT
              value: "true"
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
            - name: multicloud-root
              mountPath: /var/lib/multicloud
          securityContext:
            privileged: true
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: redis-data
          emptyDir: {}
        - name: multicloud-root
          hostPath:
            path: /var/lib/multicloud
            type: DirectoryOrCreate