apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.multicloud.fs
spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
provisioner: csi.multicloud.fs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer