# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multicloud_fs.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13multicloud_fs.proto\x12\x0emulti_cloud_fs"\x1d\n\rExistsRequest\x12\x0c\n\x04path\x18\x01 \x01(\t" \n\x0e\x45xistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08"\x1e\n\x0eGetAttrRequest\x12\x0c\n\x04path\x18\x01 \x01(\t"\xbb\x01\n\x0fGetAttrResponse\x12\x0f\n\x07st_mode\x18\x01 \x01(\x03\x12\x0e\n\x06st_ino\x18\x02 \x01(\x03\x12\x0e\n\x06st_dev\x18\x03 \x01(\x03\x12\x10\n\x08st_nlink\x18\x04 \x01(\x03\x12\x0e\n\x06st_uid\x18\x05 \x01(\x03\x12\x0e\n\x06st_gid\x18\x06 \x01(\x03\x12\x0f\n\x07st_size\x18\x07 \x01(\x03\x12\x10\n\x08st_atime\x18\x08 \x01(\x02\x12\x10\n\x08st_mtime\x18\t \x01(\x02\x12\x10\n\x08st_ctime\x18\n \x01(\x02".\n\x0eReadDirRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x03""\n\x0fReadDirResponse\x12\x0f\n\x07\x65ntries\x18\x01 \x03(\t"9\n\x0bReadRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x03\x12\x0c\n\x04size\x18\x03 \x01(\x03"\x1c\n\x0cReadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xb8\x02\n\nOperations\x12I\n\x06\x45xists\x12\x1d.multi_cloud_fs.ExistsRequest\x1a\x1e.multi_cloud_fs.ExistsResponse"\x00\x12L\n\x07GetAttr\x12\x1e.multi_cloud_fs.GetAttrRequest\x1a\x1f.multi_cloud_fs.GetAttrResponse"\x00\x12L\n\x07ReadDir\x12\x1e.multi_cloud_fs.ReadDirRequest\x1a\x1f.multi_cloud_fs.ReadDirResponse"\x00\x12\x43\n\x04Read\x12\x1b.multi_cloud_fs.ReadRequest\x1a\x1c.multi_cloud_fs.ReadResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "multicloud_fs_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EXISTSREQUEST"]._serialized_start = 39
    _globals["_EXISTSREQUEST"]._serialized_end = 68
    _globals["_EXISTSRESPONSE"]._serialized_start = 70
    _globals["_EXISTSRESPONSE"]._serialized_end = 102
    _globals["_GETATTRREQUEST"]._serialized_start = 104
    _globals["_GETATTRREQUEST"]._serialized_end = 134
    _globals["_GETATTRRESPONSE"]._serialized_start = 137
    _globals["_GETATTRRESPONSE"]._serialized_end = 324
    _globals["_READDIRREQUEST"]._serialized_start = 326
    _globals["_READDIRREQUEST"]._serialized_end = 372
    _globals["_READDIRRESPONSE"]._serialized_start = 374
    _globals["_READDIRRESPONSE"]._serialized_end = 408
    _globals["_READREQUEST"]._serialized_start = 410
    _globals["_READREQUEST"]._serialized_end = 467
    _globals["_READRESPONSE"]._serialized_start = 469
    _globals["_READRESPONSE"]._serialized_end = 497
    _globals["_OPERATIONS"]._serialized_start = 500
    _globals["_OPERATIONS"]._serialized_end = 812
# @@protoc_insertion_point(module_scope)
