# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

import multicloud_fs_pb2 as multicloud__fs__pb2

GRPC_GENERATED_VERSION = "1.64.1"
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = "1.65.0"
SCHEDULED_RELEASE_DATE = "June 25, 2024"
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in multicloud_fs_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
        + f" This warning will become an error in {EXPECTED_ERROR_RELEASE},"
        + f" scheduled for release on {SCHEDULED_RELEASE_DATE}.",
        RuntimeWarning,
    )


class OperationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exists = channel.unary_unary(
            "/multi_cloud_fs.Operations/Exists",
            request_serializer=multicloud__fs__pb2.ExistsRequest.SerializeToString,
            response_deserializer=multicloud__fs__pb2.ExistsResponse.FromString,
            _registered_method=True,
        )
        self.GetAttr = channel.unary_unary(
            "/multi_cloud_fs.Operations/GetAttr",
            request_serializer=multicloud__fs__pb2.GetAttrRequest.SerializeToString,
            response_deserializer=multicloud__fs__pb2.GetAttrResponse.FromString,
            _registered_method=True,
        )
        self.ReadDir = channel.unary_unary(
            "/multi_cloud_fs.Operations/ReadDir",
            request_serializer=multicloud__fs__pb2.ReadDirRequest.SerializeToString,
            response_deserializer=multicloud__fs__pb2.ReadDirResponse.FromString,
            _registered_method=True,
        )
        self.Read = channel.unary_unary(
            "/multi_cloud_fs.Operations/Read",
            request_serializer=multicloud__fs__pb2.ReadRequest.SerializeToString,
            response_deserializer=multicloud__fs__pb2.ReadResponse.FromString,
            _registered_method=True,
        )


class OperationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Exists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAttr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReadDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_OperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Exists": grpc.unary_unary_rpc_method_handler(
            servicer.Exists,
            request_deserializer=multicloud__fs__pb2.ExistsRequest.FromString,
            response_serializer=multicloud__fs__pb2.ExistsResponse.SerializeToString,
        ),
        "GetAttr": grpc.unary_unary_rpc_method_handler(
            servicer.GetAttr,
            request_deserializer=multicloud__fs__pb2.GetAttrRequest.FromString,
            response_serializer=multicloud__fs__pb2.GetAttrResponse.SerializeToString,
        ),
        "ReadDir": grpc.unary_unary_rpc_method_handler(
            servicer.ReadDir,
            request_deserializer=multicloud__fs__pb2.ReadDirRequest.FromString,
            response_serializer=multicloud__fs__pb2.ReadDirResponse.SerializeToString,
        ),
        "Read": grpc.unary_unary_rpc_method_handler(
            servicer.Read,
            request_deserializer=multicloud__fs__pb2.ReadRequest.FromString,
            response_serializer=multicloud__fs__pb2.ReadResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "multi_cloud_fs.Operations", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "multi_cloud_fs.Operations", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class Operations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Exists(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/multi_cloud_fs.Operations/Exists",
            multicloud__fs__pb2.ExistsRequest.SerializeToString,
            multicloud__fs__pb2.ExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetAttr(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/multi_cloud_fs.Operations/GetAttr",
            multicloud__fs__pb2.GetAttrRequest.SerializeToString,
            multicloud__fs__pb2.GetAttrResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReadDir(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/multi_cloud_fs.Operations/ReadDir",
            multicloud__fs__pb2.ReadDirRequest.SerializeToString,
            multicloud__fs__pb2.ReadDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Read(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/multi_cloud_fs.Operations/Read",
            multicloud__fs__pb2.ReadRequest.SerializeToString,
            multicloud__fs__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
