apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multicloud-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: multicloud-csi-sc

---

apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  nodeSelector:
    node: worker1
  containers:
    - name: app
      image: alpine
      command: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: multicloud-storage
          mountPath: /data
  volumes:
    - name: multicloud-storage
      persistentVolumeClaim:
        claimName: multicloud-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multicloud-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: multicloud-csi-sc

---

apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
spec:
  nodeSelector:
    node: worker2
  containers:
    - name: app
      image: alpine
      command: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: multicloud-storage
          mountPath: /data
  volumes:
    - name: multicloud-storage
      persistentVolumeClaim:
        claimName: multicloud-pvc-2